### ISSUE TITLE
The collector ID is "20180608", but the COLLECTOR_ID array's length is 4. How to transfer it?

### ISSUE THREAD

**Issue by FangHuaiAn** [google-pay/smart-tap-sample-app#4]
// Collector ID is hardcoded to `20180608` for this sample app
static final byte[] COLLECTOR_ID = new byte[]{(byte) 0x01, (byte) 0x33, (byte) 0xEE, (byte) 0x80};

**Comment by ContactlessWiki** [comment]
Open Windows Calculator, set to Programming mode, type in "20180608," and you'll see the converted form in HEX.

**Comment by FangHuaiAn** [comment]
"Collector ID" need to transfer to HEX format.
